apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apibus2.mybusservice.eu
spec:
  secretName: api.mybusservice.eu
  dnsNames: 
  - api.mybusservice.eu
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer