apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: api-test.mybusservice.eu
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: {{ .Chart.Name }}