apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tictacingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /test
          pathType: Prefix
          backend:
            service:
              name: tictactoeservice
              port:
                number: 31112