apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: tictactoe
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tictactoe
  template:
    metadata:
      labels:
        app: tictactoe
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: {{ .Chart.Name }}
        image: docker.io/locoselli/beyondimages:tictactoe
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: regcred
